### ISSUE TITLE
Severe Translation Bug with links in CKEditor

### ISSUE THREAD

**Issue by christophrunkel** [nitsan-technologies/ns_t3ai#5]
We have a problem when translating content elements with t3ai (connected mode, german english)

Environment: Typo3 12.4.16 (non composer) / NS AI 3.1.2 Premium / PHP 8.2.18

A normal bodytext field (Typo3 text element, field bodytext) translates properly:

```
<p>
    <a href="t3://page?uid=29">Kontakt aufnehmen</a>
</p>
```

results in 

```
<p>
    <a href="t3://page?uid=29">Make Contact</a>
</p>
```

which is OK 

Whereagainst when adding an allowed class **btn btn-success** in CKEditor, resulting source code (same content element and field)

```
<p>
    <a class="btn btn-success" href="t3://page?uid=29">Kontakt aufnehmen</a>
</p>
```

results in :

```
<p>
    Make Contact
</p>
```

With all link information lost. The target page #29 in target language english exists.

Thanks in advance for quick response.

**Comment by nitsan-technologies** [comment]
Hey @christophrunkel 
Nice to e-meet you!

Thank you for contacting us. I appreciate your detailed description of the issue.

We've tested your TYPO3 instance as your mentioned, and everything appears to be functioning correctly. Please review the screencast at https://drive.google.com/file/d/1uCrQIjIsWHLHDMRSzVdpTweHNm-OWjIc/view?usp=sharing.

To assist you promptly, please provide access to your TYPO3 instance via a private ticket at https://t3planet.com/support.

Cheers!

**Comment by christophrunkel** [comment]
I just found out. The error only appears when using  Model (ai engine settings.model [options]) **GPT-4.** With GPT-4o everything works and the resulting source code is:

```
<p>
    <a class="btn btn-success" href="t3://page?uid=29">Get in touch</a>
</p>
```

That should help to reproduce the error. For my case the issue is not severe anymore, since i found a solution.
If you still need access to my Typo3-Instance i can enable that within the next days.

Christoph

**Comment by nitsan-technologies** [comment]
Hey @christophrunkel 

Thank you for your prompt response. I'm glad to hear everything is functioning correctly.

Just to let you know, we've also tested it with GPT-4, and it appears to be working fine too. You can check it out at https://drive.google.com/file/d/1jezQHl1fdFocp3nSbrI5tyq-m4idYj5M/view?usp=sharing

Cheers!
